import os


NOTION_TOKEN = "NOTION_TOKEN"
NOTION_RESCUETIME_URL= "NOTION_RESCUETIME_URL"
NOTION_CLICKUP_URL= "NOTION_CLICKUP_URL"
NOTION_TOGGL_URL="NOTION_TOGGL_URL"
NOTION_JIRA_URL="NOTION_JIRA_URL"
NOTION_GOALS_URL="NOTION_GOALS_URL"
NOTION_PROJECT_URL="NOTION_PROJECT_URL"
NOTION_TASKS_URL="NOTION_TASKS_URL"
NOTION_CALENDAR_URL="NOTION_CALENDAR_URL"
NOTION_BOOK_LIBRARY_URL="NOTION_BOOK_LIBRARY_URL"
NOTION_VIDEO_LIBRARY_URL='NOTION_VIDEO_LIBRARY_URL'
NOTION_TRACKING_DAILY_URL="NOTION_TRACKING_DAILY_URL"
NOTION_HABIT_ROUTINE_URL="NOTION_HABIT_ROUTINE_URL"
RESCUETIME_URL="RESCUETIME_URL"
TOGGL_URL="TOGGL_URL"
TOGGL_KEY="TOGGL_KEY"
JIRA_STOCKY_URL="JIRA_STOCKY_URL"
JIRA_STOCKY_USER="JIRA_STOCKY_USER"
JIRA_STOCKY_KEY="JIRA_STOCKY_KEY"
JIRA_PERSONAL_URL="JIRA_PERSONAL_URL"
JIRA_PERSONAL_USER="JIRA_PERSONAL_USER"
JIRA_PERSONAL_KEY="JIRA_PERSONAL_KEY"
GOOGLE_CREDS_OFFICE_PATH="GOOGLE_CREDS_OFFICE_PATH"
GOOGLE_CREDS_PERSONAL_PATH="GOOGLE_CREDS_PERSONAL_PATH"
AIRTABLE_API_KEY="AIRTABLE_API_KEY"


CONFIG = {}


def set_from_enviorn(val):
    CONFIG[val] = os.environ[val].replace('"', '')

set_from_enviorn(NOTION_TOKEN)
set_from_enviorn(NOTION_RESCUETIME_URL)
set_from_enviorn(NOTION_CLICKUP_URL)
set_from_enviorn(NOTION_CLICKUP_URL)
set_from_enviorn(NOTION_TOGGL_URL)
set_from_enviorn(NOTION_JIRA_URL)
set_from_enviorn(NOTION_GOALS_URL)
set_from_enviorn(NOTION_TASKS_URL)
set_from_enviorn(NOTION_CALENDAR_URL)
set_from_enviorn(NOTION_BOOK_LIBRARY_URL)
set_from_enviorn(NOTION_VIDEO_LIBRARY_URL)
set_from_enviorn(NOTION_TRACKING_DAILY_URL)
set_from_enviorn(RESCUETIME_URL)
set_from_enviorn(TOGGL_URL)
set_from_enviorn(TOGGL_KEY)
set_from_enviorn(JIRA_STOCKY_URL)
set_from_enviorn(JIRA_STOCKY_USER)
set_from_enviorn(JIRA_STOCKY_KEY)
set_from_enviorn(JIRA_PERSONAL_URL)
set_from_enviorn(JIRA_PERSONAL_USER)
set_from_enviorn(JIRA_PERSONAL_KEY)
set_from_enviorn(AIRTABLE_API_KEY)
set_from_enviorn(NOTION_PROJECT_URL)
set_from_enviorn(NOTION_HABIT_ROUTINE_URL)




