version: '3.7'

services:
  growth:
    build:
      context: ../
      dockerfile: Dockerfile
    env_file:
      - ../envfile
    volumes:
      - ../growth:/growth/
      - ../sql:/sql/
      - ../scripts:/scripts/
      - ../config.yml:/config.yml
    entrypoint:
      - run-dev.sh
    command:
      - /bin/bash
    stdin_open: true
    tty: true
